load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "viz",
    srcs = ["viz/vizlib.cpp"],
    hdrs = [
        "viz/vizlib.h",
        "viz/vizlib_bal.h",
        "viz/g2o_viz.h"#include "estimation/bundle_adjustment/g2o_ba.h"
    ],
    deps = [
        "//third_party:pangolin",
        "@eigen",
        "@sophus",
    ],
)

cc_library(
    name = "util",
    srcs = [
        "util/eval.cpp",
        "util/utillib.cpp",
    ],
    hdrs = [
        "util/bal.h",
        "util/eval.h",
        "util/g2o_io.h",
        "util/utillib.h",
    ],
    deps = [
        "//:viz",
        "@eigen",
        "@sophus",
    ],
)

cc_library(
    name = "frontend",
    srcs = [
        "frontend/direct_method.cpp",
        "frontend/optical_flow.cpp",
        "frontend/orb.cpp",
    ],
    hdrs = [
        "frontend/direct_method.h",
        "frontend/optical_flow.h",
        "frontend/orb.h",
        "frontend/point_sampling.h",
    ],
    deps = [
        "//:estimation",
        "//:geometry",
        "@eigen",
        "@opencv",
        "@sophus",
    ],
)

cc_library(
    name = "geometry",
    srcs = [
        "geometry/reprojection.cpp",
    ],
    hdrs = [
        "geometry/bilinear.h",
        "geometry/calib.h",
        "geometry/coordinate_utils.h",
        "geometry/reprojection.h",
        "geometry/rotation.h",
    ],
    deps = [
        "@eigen",
        "@opencv",
        "@sophus",
    ],
)

cc_library(
    name = "estimation",
    srcs = [
        "estimation/epipolar/epipolar.cpp",
        "estimation/icp/icp_nonlinear.cpp",
        "estimation/pnp/pnp_g2o.cpp",
    ],
    hdrs = [
        "estimation/bundle_adjustment/g2o_ba.h",
        "estimation/bundle_adjustment/snavely_reprojection.h",
        "estimation/epipolar/epipolar.h",
        "estimation/icp/icp.h",
        "estimation/icp/icp_nonlinear.h",
        "estimation/icp/icp_svd.h",
        "estimation/pnp/pnp.h",
        "estimation/pnp/pnp_g2o.h",
        "estimation/pnp/pnp_naive.h",
        "estimation/pose_graph/pose_edge_g2o.h",
        "estimation/pose_graph/pose_vertex_g2o.h",
    ],
    deps = [
        "//:geometry",
        "//:util",
        "//third_party:g2o",
        "@eigen",
        "@opencv",
        "@sophus",
    ],
)

cc_binary(
    name = "vslam",
    srcs = ["vslam.cpp"],
    deps = [
        "//:estimation",
        "//:viz",
        "//third_party:g2o",
        "@eigen",
    ],
)

cc_binary(
    name="dbow",
    srcs=["dbow.cpp"],
    deps=[
        "//third_party:dbow3"
    ]
)
